import 'package:flutter/material.dart';
import 'package:flutterapp/mecanicaautomotrizapp/generatedajusteswidget6/generated/GeneratedRectangle5Widget.dart';
import 'package:flutterapp/mecanicaautomotrizapp/generatedajusteswidget6/generated/GeneratedMenuinferiorWidget3.dart';
import 'package:flutterapp/mecanicaautomotrizapp/generatedajusteswidget6/generated/GeneratedAjustesdelacuentaWidget.dart';
import 'package:flutterapp/mecanicaautomotrizapp/generatedajusteswidget6/generated/GeneratedAccedeatucuentaWidget2.dart';
import 'package:flutterapp/mecanicaautomotrizapp/generatedajusteswidget6/generated/GeneratedMecnicaAutomotrizLosMelndezWidget2.dart';
import 'package:flutterapp/mecanicaautomotrizapp/generatedajusteswidget6/generated/GeneratedBotonWidget3.dart';
import 'package:flutterapp/mecanicaautomotrizapp/generatedajusteswidget6/generated/GeneratedImg43Widget.dart';

/* Frame Ajustes
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAjustesWidget6 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 195, 193, 193),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 806.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 90.0,
                child: GeneratedMenuinferiorWidget3(),
              ),
              Positioned(
                left: 106.0,
                top: 300.0,
                right: null,
                bottom: null,
                width: 205.0,
                height: 41.0,
                child: GeneratedAjustesdelacuentaWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 300.0,
                child: GeneratedRectangle5Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 275.326171875,
                child: GeneratedImg43Widget(),
              ),
              Positioned(
                left: 17.0,
                top: 93.0,
                right: null,
                bottom: null,
                width: 382.0,
                height: 91.0,
                child: GeneratedMecnicaAutomotrizLosMelndezWidget2(),
              ),
              Positioned(
                left: 57.0,
                top: 364.0,
                right: null,
                bottom: null,
                width: 302.0,
                height: 275.0,
                child: GeneratedAccedeatucuentaWidget2(),
              ),
              Positioned(
                left: 38.0,
                top: 660.0,
                right: null,
                bottom: null,
                width: 339.0,
                height: 60.0,
                child: GeneratedBotonWidget3(),
              )
            ]),
      ),
    ));
  }
}
