import 'package:flutter/material.dart';
import 'package:flutterapp/mecanicaautomotrizapp/generatedmenuinferiorwidget/generated/GeneratedAjustesWidget.dart';
import 'package:flutterapp/mecanicaautomotrizapp/generatedmenuinferiorwidget/generated/GeneratedRectangle4Widget.dart';
import 'package:flutterapp/mecanicaautomotrizapp/generatedmenuinferiorwidget/generated/GeneratedEllipse1Widget.dart';
import 'package:flutterapp/mecanicaautomotrizapp/generatedmenuinferiorwidget/generated/GeneratedHomeWidget.dart';
import 'package:flutterapp/mecanicaautomotrizapp/generatedmenuinferiorwidget/generated/GeneratedAddcircleWidget.dart';

/* Component Menu inferior
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMenuinferiorWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 414.0,
      height: 90.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            ClipRRect(
              borderRadius: BorderRadius.zero,
              child: Container(
                color: Color.fromARGB(255, 195, 193, 193),
              ),
            ),
            Positioned(
              left: 0.0,
              top: 15.0,
              right: null,
              bottom: null,
              width: 414.0,
              height: 75.0,
              child: GeneratedRectangle4Widget(),
            ),
            Positioned(
              left: 314.0,
              top: 27.0,
              right: null,
              bottom: null,
              width: 46.0,
              height: 45.0,
              child: GeneratedAjustesWidget(),
            ),
            Positioned(
              left: 67.0,
              top: 24.0,
              right: null,
              bottom: null,
              width: 33.0,
              height: 45.0,
              child: GeneratedHomeWidget(),
            ),
            Positioned(
              left: 172.0,
              top: -25.0,
              right: null,
              bottom: null,
              width: 70.0,
              height: 74.24242401123047,
              child: GeneratedEllipse1Widget(),
            ),
            Positioned(
              left: 182.0,
              top: -13.0,
              right: null,
              bottom: null,
              width: 50.0,
              height: 50.0,
              child: GeneratedAddcircleWidget(),
            )
          ]),
    ));
  }
}
