import 'package:flutter/material.dart';
import 'package:flutterapp/mecanicaautomotrizapp/generatedloginwidget/generated/GeneratedAccedeatucuentaWidget.dart';
import 'package:flutterapp/mecanicaautomotrizapp/generatedloginwidget/generated/GeneratedInputWidget.dart';
import 'package:flutterapp/mecanicaautomotrizapp/generatedloginwidget/generated/GeneratedGroup1Widget.dart';
import 'package:flutterapp/mecanicaautomotrizapp/generatedloginwidget/generated/GeneratedOlvidastetucontraseaWidget.dart';
import 'package:flutterapp/mecanicaautomotrizapp/generatedloginwidget/generated/GeneratedBienvenidodevueltaWidget.dart';
import 'package:flutterapp/mecanicaautomotrizapp/generatedloginwidget/generated/GeneratedRectangle1Widget.dart';
import 'package:flutterapp/mecanicaautomotrizapp/generatedloginwidget/generated/GeneratedInputWidget1.dart';
import 'package:flutterapp/mecanicaautomotrizapp/generatedloginwidget/generated/GeneratedBotonWidget.dart';

/* Frame Login
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoginWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 195, 193, 193),
                ),
              ),
              Positioned(
                left: -25.0,
                top: -40.0,
                right: null,
                bottom: null,
                width: 462.0535583496094,
                height: 500.0,
                child: GeneratedGroup1Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 396.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 500.0,
                child: GeneratedRectangle1Widget(),
              ),
              Positioned(
                left: 123.0,
                top: 525.0,
                right: null,
                bottom: null,
                width: 170.0,
                height: 41.0,
                child: GeneratedAccedeatucuentaWidget(),
              ),
              Positioned(
                left: 49.0,
                top: 479.0,
                right: null,
                bottom: null,
                width: 318.0,
                height: 48.0,
                child: GeneratedBienvenidodevueltaWidget(),
              ),
              Positioned(
                left: 36.0,
                top: 573.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 60.0,
                child: GeneratedInputWidget(),
              ),
              Positioned(
                left: 37.0,
                top: 646.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 60.0,
                child: GeneratedInputWidget1(),
              ),
              Positioned(
                left: 102.0,
                top: 725.0,
                right: null,
                bottom: null,
                width: 210.0,
                height: 25.0,
                child: GeneratedOlvidastetucontraseaWidget(),
              ),
              Positioned(
                left: 37.0,
                top: 768.0,
                right: null,
                bottom: null,
                width: 339.0,
                height: 60.0,
                child: GeneratedBotonWidget(),
              )
            ]),
      ),
    ));
  }
}
