import 'package:flutter/material.dart';
import 'package:flutterapp/mecanicaautomotrizapp/generatedcambiardatoswidget/generated/GeneratedInputWidget7.dart';
import 'package:flutterapp/mecanicaautomotrizapp/generatedcambiardatoswidget/generated/GeneratedInputWidget9.dart';
import 'package:flutterapp/mecanicaautomotrizapp/generatedcambiardatoswidget/generated/GeneratedImg43Widget1.dart';
import 'package:flutterapp/mecanicaautomotrizapp/generatedcambiardatoswidget/generated/GeneratedBotonWidget4.dart';
import 'package:flutterapp/mecanicaautomotrizapp/generatedcambiardatoswidget/generated/GeneratedInputWidget10.dart';
import 'package:flutterapp/mecanicaautomotrizapp/generatedcambiardatoswidget/generated/GeneratedRectangle5Widget1.dart';
import 'package:flutterapp/mecanicaautomotrizapp/generatedcambiardatoswidget/generated/GeneratedBotonWidget5.dart';
import 'package:flutterapp/mecanicaautomotrizapp/generatedcambiardatoswidget/generated/GeneratedMecnicaAutomotrizLosMelndezWidget3.dart';
import 'package:flutterapp/mecanicaautomotrizapp/generatedcambiardatoswidget/generated/GeneratedCambiardatosWidget1.dart';
import 'package:flutterapp/mecanicaautomotrizapp/generatedcambiardatoswidget/generated/GeneratedMenuinferiorWidget4.dart';
import 'package:flutterapp/mecanicaautomotrizapp/generatedcambiardatoswidget/generated/GeneratedInputWidget8.dart';

/* Frame Cambiar datos
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCambiardatosWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 896.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 195, 193, 193),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 806.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 90.0,
                child: GeneratedMenuinferiorWidget4(),
              ),
              Positioned(
                left: 134.0,
                top: 300.0,
                right: null,
                bottom: null,
                width: 148.0,
                height: 41.0,
                child: GeneratedCambiardatosWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 300.0,
                child: GeneratedRectangle5Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 414.0,
                height: 275.326171875,
                child: GeneratedImg43Widget1(),
              ),
              Positioned(
                left: 17.0,
                top: 93.0,
                right: null,
                bottom: null,
                width: 382.0,
                height: 91.0,
                child: GeneratedMecnicaAutomotrizLosMelndezWidget3(),
              ),
              Positioned(
                left: 37.0,
                top: 640.0,
                right: null,
                bottom: null,
                width: 339.0,
                height: 60.0,
                child: GeneratedBotonWidget4(),
              ),
              Positioned(
                left: 38.0,
                top: 710.0,
                right: null,
                bottom: null,
                width: 339.0,
                height: 60.0,
                child: GeneratedBotonWidget5(),
              ),
              Positioned(
                left: 37.0,
                top: 350.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 60.0,
                child: GeneratedInputWidget7(),
              ),
              Positioned(
                left: 36.0,
                top: 420.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 60.0,
                child: GeneratedInputWidget8(),
              ),
              Positioned(
                left: 36.0,
                top: 490.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 60.0,
                child: GeneratedInputWidget9(),
              ),
              Positioned(
                left: 36.0,
                top: 560.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 60.0,
                child: GeneratedInputWidget10(),
              )
            ]),
      ),
    ));
  }
}
